### PR TITLE
Added VerifAI

### PR DESCRIPTION
**Pull request by YinzhuS**

### CODE REVIEW

**Review by aolofsson — CHANGES_REQUESTED** [review]
1. Category is EDA, not AI.
2. No claims in descriptiion,ie no 100x.

**Comment by YinzhuS** [comment]
Hi @aolofsson 

Thanks for your comment!
For the 2nd point, I have changed the description to be:

> Speeding up Hardware & Software Verification using LLMs & Reinforcement Learning

This is exactly 80 characters.

However for your 1st point, we are actually an AI company instead of an EDA company. Can we just leave the Technology /  category as **AI**?

Thank you!

**Comment by afaerber** [comment]
This repository has `semiconductor` in its name, and you don't appear to be producing any AI accelerator chips or IP yourselves like the companies in the `AI` category. So if you want to be listed here, `EDA` is @aolofsson's software category here, even if that software makes use of AI technology. Hope that explains.

**Comment by YinzhuS** [comment]
Hi @afaerber and @aolofsson 

Thanks for your guidance! I have changed the category of VerifAI to EDA in this PR.

Could you please help to check and approve this PR?

Thanks!

**Comment by aolofsson** [comment]
Great, thanks!

**Pull request merged**
